# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Python image as the base image
FROM python:3.12-slim AS builder

# Set the working directory
WORKDIR /app

# Copy the necessary files
COPY pyproject.toml /app/
COPY src /app/src

# Install the project's dependencies
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir hatchling \
    && hatch build

# Final stage
FROM python:3.12-slim

# Set the working directory
WORKDIR /app

# Copy the build output from the builder stage
COPY --from=builder /app/src /app/src

# Install the package
RUN pip install --no-cache-dir /app/src

# Set environment variables for Bear API
ENV BEAR_API_TOKEN=<YOUR_API_TOKEN_HERE>

# Set the entry point
ENTRYPOINT ["python", "-m", "mcp_bear"]
